#!/usr/bin/env python3
"""Generate the AgentState JSON Schema from the spec's normative rules.

The schema is checked into ``spec/agent-state.schema.json`` and regenerated by
this script. CI regenerates it and fails if the result differs from what is
committed, so the published schema cannot drift away from the implementation
without someone noticing.

Written by hand against ``spec/state-image.md`` rather than derived from the
dataclasses by reflection. Reflection would produce a schema that agrees with
the code by construction -- including where the code is wrong -- which is
exactly the disagreement worth catching.

Usage:
    python scripts/generate_schema.py            # write the schema
    python scripts/generate_schema.py --check    # verify it is up to date
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from continuum.model import FORMAT_VERSION, ExecutionStatus, MemoryKind

SCHEMA_PATH = Path("spec/agent-state.schema.json")

DIGEST = {"type": "string", "pattern": "^sha256:[0-9a-f]{64}$"}
IDENTIFIER = {"type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"}
TIMESTAMP = {"type": "string", "description": "RFC 3339 UTC, second precision"}
CAPABILITY_NAME = {
    "type": "string",
    "pattern": "^[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*$",
    "description": "Dotted capability name. Requirements must not contain wildcards.",
}


def build() -> dict:
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/sandrexa1111/continuum-agent/spec/agent-state.schema.json",
        "title": "Continuum Agent State",
        "description": (
            f"An agent's portable execution state, format version {FORMAT_VERSION}. "
            "Normative prose lives in spec/state-image.md; this schema encodes the "
            "structural rules only. Constraints it cannot express -- canonical "
            "encoding, digest agreement, artifact-graph acyclicity, event sequence "
            "ordering, and the requires/optional disjointness rule -- are stated "
            "there and enforced by AgentState.validate()."
        ),
        "type": "object",
        "required": ["format_version", "identity"],
        "additionalProperties": True,
        "$comment": (
            "additionalProperties is true by design. Readers must preserve unknown "
            "top-level fields and re-emit them unchanged; see spec/compatibility.md "
            "section 2. A schema that forbade them would make every older validator "
            "reject documents it is required to round-trip."
        ),
        "properties": {
            "format_version": {
                "type": "string",
                "pattern": "^[0-9]+\\.[0-9]+$",
                "examples": [FORMAT_VERSION],
            },
            "identity": {
                "type": "object",
                "required": ["agent_id"],
                "properties": {
                    "agent_id": IDENTIFIER,
                    "display_name": {"type": "string"},
                    "created_at": TIMESTAMP,
                },
            },
            "objective": {
                "type": "object",
                "properties": {
                    "goal": {"type": "string"},
                    "constraints": {"type": "array", "items": {"type": "string"}},
                    "success_criteria": {"type": "array", "items": {"type": "string"}},
                },
            },
            "execution": {
                "type": "object",
                "properties": {
                    "current_task": {"type": "string"},
                    "status": {"enum": [s.value for s in ExecutionStatus]},
                    "step": {"type": "integer", "minimum": 0},
                    "cursor": {
                        "type": "object",
                        "description": (
                            "Adapter-defined resumption pointer. Readers must "
                            "preserve it and must not interpret it."
                        ),
                    },
                    "pending_tasks": {"type": "array", "items": {"type": "string"}},
                },
            },
            "provider": {
                "type": "object",
                "properties": {
                    "adapter": {"type": "string"},
                    "provider": {"type": "string"},
                    "model": {"type": "string"},
                    "params": {"type": "object"},
                    "opaque": {
                        "type": "object",
                        "description": (
                            "Provider-side state that does not survive migration to "
                            "a different provider. Nothing the agent needs to "
                            "function may live here."
                        ),
                    },
                },
            },
            "memory": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["id", "kind", "content"],
                    "properties": {
                        "id": IDENTIFIER,
                        "kind": {"enum": [k.value for k in MemoryKind]},
                        "content": {"type": "string"},
                        "created_at": TIMESTAMP,
                        "source": {"type": "string"},
                        "importance": {"type": "number", "minimum": 0, "maximum": 1},
                        "pinned": {"type": "boolean"},
                        "transformed": {
                            "type": "boolean",
                            "description": (
                                "True when this entry summarizes other state rather "
                                "than recording an observation. Producers must set it "
                                "on generated summaries."
                            ),
                        },
                        "attributes": {"type": "object"},
                    },
                },
            },
            "context": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["role", "content"],
                    "properties": {
                        "role": {"type": "string"},
                        "content": {"type": "string"},
                        "name": {"type": "string"},
                        "tool_call_id": {"type": "string"},
                        "pinned": {"type": "boolean"},
                        "metadata": {"type": "object"},
                    },
                },
            },
            "capabilities": {
                "type": "object",
                "properties": {
                    "requires": {"type": "array", "items": CAPABILITY_NAME},
                    "optional": {"type": "array", "items": CAPABILITY_NAME},
                    "granted": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "pattern": "^(\\*|[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*(\\.\\*)?)$",
                            "description": "Grants may end in '.*' to cover a namespace.",
                        },
                    },
                },
            },
            "environment": {
                "type": "object",
                "properties": {
                    "os": {"type": "string"},
                    "arch": {"type": "string"},
                    "runtime": {"type": "string"},
                    "runtime_version": {"type": "string"},
                    "workspace_digest": {"type": "string"},
                    "git_commit": {"type": "string"},
                    "env_var_names": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Names only. Values must never be captured.",
                    },
                    "tools": {"type": "array", "items": {"type": "string"}},
                },
            },
            "artifacts": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["id", "path"],
                    "properties": {
                        "id": IDENTIFIER,
                        "path": {
                            "type": "string",
                            "pattern": "^(?!/)(?!.*\\.\\.).*$",
                            "description": "Relative; must not be absolute or contain '..'.",
                        },
                        "digest": DIGEST,
                        "media_type": {"type": "string"},
                        "derived_from": {
                            "type": "array",
                            "items": IDENTIFIER,
                            "description": (
                                "Artifact ids in this same document. The resulting "
                                "graph must be acyclic."
                            ),
                        },
                        "created_at": TIMESTAMP,
                    },
                },
            },
            "events": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["seq", "type"],
                    "properties": {
                        "seq": {"type": "integer", "minimum": 0},
                        "ts": TIMESTAMP,
                        "type": {"type": "string"},
                        "data": {"type": "object"},
                    },
                },
            },
            "lineage": {
                "type": "object",
                "properties": {
                    "parent": DIGEST,
                    "root": DIGEST,
                    "forked_from": DIGEST,
                    "fork_label": {"type": "string"},
                    "generation": {"type": "integer", "minimum": 0},
                },
            },
            "runtime_opaque": {
                "type": "object",
                "description": ("Adapter-private state. Dropped when the adapter changes."),
            },
        },
    }


def main(argv: list[str]) -> int:
    schema = json.dumps(build(), indent=2, sort_keys=True) + "\n"
    root = Path(__file__).resolve().parents[1]
    target = root / SCHEMA_PATH

    if "--check" in argv:
        if not target.exists():
            print(f"{SCHEMA_PATH} is missing; run scripts/generate_schema.py", file=sys.stderr)
            return 1
        if target.read_text(encoding="utf-8") != schema:
            print(
                f"{SCHEMA_PATH} is out of date; run scripts/generate_schema.py",
                file=sys.stderr,
            )
            return 1
        print(f"{SCHEMA_PATH} is up to date")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(schema, encoding="utf-8")
    print(f"wrote {SCHEMA_PATH} ({len(schema)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
